### ISSUE TITLE
Independent style for each passed milestone

### ISSUE THREAD

**Issue by madmanblues** [stemo40/milestones#1]
Hi, I was wondering if it would be possible to add as an option an array in which specify the style of each check. In example if a milestone has been passed with delay it can be a red check-mark, while if it was passed on time the check-mark can be green.

Thanks for this great plugin and let me know if this feature is possible.

**Comment by madmanblues** [comment]
I've updated the js changing the checkclass option into an array and the updated the line that sets the checkclass:
[line 54] `var icon = '<i class="fa fa-check '+checkclass[x]+'"></i>';`

In this way, for each check you can set the css class. 
I'm sure that are better and more flexible solutions but for a quick fix it's making the trick.

**Comment by stemo40** [comment]
Hi, thanks for the question!

I added a "missed" class to the CSS file, and added code to the plugin to handle an array for which milestone did not meet the deadline. So, download the updated files and do the initialization like this:

$('#ms1').milestones({
  position: 4,
  checks: 3,
  missed: [2,4],
  labels: ["Pre-Submission","Added","Concept","Another","Preliminary","Interject","Final"]
});

The 'missed" option sets which milestone will get the red checkmark, and in this example the 2nd and 4th checkmark is red.

Hope that works for you.

**Comment by madmanblues** [comment]
That's great... much better than my dirty solution :-P

Thanks!

**Comment by stemo40** [comment]
You're welcome.

**Comment by madmanblues** [comment]
I've downloaded the new version and it's not working anymore on my side.
I'm getting the error on the test.html as well  

![image](https://user-images.githubusercontent.com/7707578/43005193-63325102-8c32-11e8-8702-ca60d5c0d5c4.png)
